import marimo

__generated_with = "0.23.16"
app = marimo.App(width="full")


@app.cell
def _():
    import math
    from pathlib import Path

    import altair as alt
    import marimo as mo
    import numpy as np
    import pandas as pd
    import plotly.graph_objects as go

    return Path, alt, go, mo, np, pd


@app.cell
def _(Path):
    # -------------------------------------------------------------------------
    # USER SETTINGS
    # -------------------------------------------------------------------------
    # This folder should contain the three CSV files generated by
    # prepare_interactive_tables.py.
    DATA_DIR = Path(
        r"C:\Lab\Processing\TG963_site1_population\interactive_tables"
    )

    POPULATION_CSV = DATA_DIR / "interactive_population_points.csv"
    PATTERN_CSV = DATA_DIR / "interactive_12pattern_responses.csv"
    DIRECTION_CSV = DATA_DIR / "interactive_8direction_responses.csv"

    PATTERN_ORDER = [
        "VAl",
        "VAr",
        "HA_leftcorner_clockwise",
        "HA_leftcorner_anticlockwise",
        "HA_rightcorner_clockwise",
        "HA_rightcorner_anticlockwise",
        "Ascent",
        "Descent",
        "EXPANSION_l",
        "EXPANSION_r",
        "CONTRACTION_left",
        "CONTRACTION_right",
    ]

    PATTERN_LABELS = {
        "VAl": "VA left",
        "VAr": "VA right",
        "HA_leftcorner_clockwise": "HA left CW",
        "HA_leftcorner_anticlockwise": "HA left CCW",
        "HA_rightcorner_clockwise": "HA right CW",
        "HA_rightcorner_anticlockwise": "HA right CCW",
        "Ascent": "Ascent",
        "Descent": "Descent",
        "EXPANSION_l": "Expansion left",
        "EXPANSION_r": "Expansion right",
        "CONTRACTION_left": "Contraction left",
        "CONTRACTION_right": "Contraction right",
    }

    SCREEN_ORDER = ["left", "front", "right"]
    DIRECTION_ORDER = [0, 45, 90, 135, 180, 225, 270, 315]

    DEFAULT_ALPHA = 0.05
    DEFAULT_POINT_SIZE = 65
    DEFAULT_COLOR_DOMAIN = 1.0
    return (
        DEFAULT_ALPHA,
        DEFAULT_COLOR_DOMAIN,
        DEFAULT_POINT_SIZE,
        DIRECTION_CSV,
        DIRECTION_ORDER,
        PATTERN_CSV,
        PATTERN_LABELS,
        PATTERN_ORDER,
        POPULATION_CSV,
        SCREEN_ORDER,
    )


@app.cell
def _(alt, pd):
    # -------------------------------------------------------------------------
    # HELPERS
    # -------------------------------------------------------------------------
    def read_csv_checked(path, required_columns, allow_empty=False):
        if not path.exists():
            raise FileNotFoundError(f"CSV not found: {path}")
        df = pd.read_csv(path, low_memory=False)
        missing = [c for c in required_columns if c not in df.columns]
        if missing:
            raise ValueError(
                f"{path.name} is missing required columns: {missing}\n"
                f"Available columns: {df.columns.tolist()}"
            )
        if df.empty and not allow_empty:
            raise ValueError(f"{path.name} contains no rows")
        return df

    def numeric_inplace(df, columns):
        out = df.copy()
        for col in columns:
            if col in out.columns:
                out[col] = pd.to_numeric(out[col], errors="coerce")
        return out

    def first_existing(columns, candidates):
        available = set(columns)
        return next((c for c in candidates if c in available), None)

    def available_stat_columns(df):
        preferred = [
            "p_motion_specific_two_sided",
            "p_ttest_two_sided",
            "q_motion_specific_two_sided",
            "q_ttest_two_sided",
            "p_motion_baseline_two_sided_screen",
            "q_motion_baseline_two_sided_screen",
            "p_direction_tuning_permutation_screen",
            "q_direction_tuning_permutation_screen",
        ]
        discovered = [
            c
            for c in df.columns
            if c.startswith(("p_", "q_", "is_"))
            or "p_value" in c.lower()
            or "q_value" in c.lower()
        ]
        ordered = []
        for col in preferred + discovered:
            if col in df.columns and col not in ordered:
                ordered.append(col)
        return ordered

    def clean_label(value):
        return str(value).replace("_", " ")

    def close_polar_frame(df, value_columns):
        if df.empty:
            return df.copy()
        pieces = []
        group_cols = [c for c in ["source_name", "unit_uid", "screen_role", "speed"] if c in df]
        if not group_cols:
            groups = [(None, df)]
        else:
            groups = df.groupby(group_cols, dropna=False, sort=False)
        for _, group in groups:
            group = group.sort_values(["direction_order", "direction"], kind="stable")
            if group.empty:
                continue
            first = group.iloc[[0]].copy()
            first["direction_plot"] = pd.to_numeric(first["direction"], errors="coerce") + 360
            current = group.copy()
            current["direction_plot"] = pd.to_numeric(current["direction"], errors="coerce")
            pieces.extend([current, first])
        if not pieces:
            return df.iloc[0:0].copy()
        result = pd.concat(pieces, ignore_index=True)
        keep_cols = list(dict.fromkeys(list(df.columns) + ["direction_plot"] + value_columns))
        return result[[c for c in keep_cols if c in result.columns]]

    def stat_table_long(df, id_columns, stat_columns):
        if df.empty or not stat_columns:
            return pd.DataFrame(columns=id_columns + ["statistic", "value"])
        existing_ids = [c for c in id_columns if c in df.columns]
        existing_stats = [c for c in stat_columns if c in df.columns]
        base = df[existing_ids + existing_stats].drop_duplicates().copy()
        return base.melt(
            id_vars=existing_ids,
            value_vars=existing_stats,
            var_name="statistic",
            value_name="value",
        )

    def empty_chart(message, width=520, height=240):
        placeholder = pd.DataFrame({"message": [message], "x": [0.5], "y": [0.5]})
        return (
            alt.Chart(placeholder)
            .mark_text(fontSize=15)
            .encode(
                x=alt.X("x:Q", axis=None, scale=alt.Scale(domain=[0, 1])),
                y=alt.Y("y:Q", axis=None, scale=alt.Scale(domain=[0, 1])),
                text="message:N",
            )
            .properties(width=width, height=height)
        )

    return (
        available_stat_columns,
        first_existing,
        numeric_inplace,
        read_csv_checked,
        stat_table_long,
    )


@app.cell
def _(
    DIRECTION_CSV,
    PATTERN_CSV,
    POPULATION_CSV,
    numeric_inplace,
    read_csv_checked,
):
    population_raw = read_csv_checked(
        POPULATION_CSV,
        [
            "source_name",
            "unit_id",
            "unit_uid",
            "pattern",
            "x_plot_um",
            "y_plot_um",
            "fraction_change",
        ],
    )
    pattern_raw = read_csv_checked(
        PATTERN_CSV,
        ["source_name", "unit_id", "unit_uid", "pattern"],
    )
    direction_raw = read_csv_checked(
        DIRECTION_CSV,
        [
            "source_name",
            "unit_id",
            "unit_uid",
            "screen_role",
            "speed",
            "direction",
            "trial_id",
            "baseline_fr_trial",
            "moving_fr_trial",
            "response_trial",
        ],
        allow_empty=True,
    )

    population_df = numeric_inplace(
        population_raw,
        [
            "x_um",
            "y_um",
            "x_plot_um",
            "y_plot_um",
            "fraction_change",
            "baseline_fr_mean",
            "moving_fr_mean",
            "pattern_order",
            "best_channel",
            "shank_id",
        ],
    )
    pattern_df = numeric_inplace(
        pattern_raw,
        [
            "pattern_order",
            "baseline_fr_mean",
            "baseline_fr_sem",
            "moving_fr_mean",
            "moving_fr_sem",
            "moving_minus_baseline_mean",
            "moving_minus_baseline_sem",
            "fraction_change",
            "n_trials",
        ],
    )
    direction_df = numeric_inplace(
        direction_raw,
        [
            "direction",
            "direction_order",
            "screen_order",
            "baseline_fr_trial",
            "moving_fr_trial",
            "response_trial",
            "fraction_change_trial",
        ],
    )

    for _frame in [population_df, pattern_df, direction_df]:
        if "unit_uid" in _frame.columns:
            _frame["unit_uid"] = _frame["unit_uid"].astype(str)
        if "source_name" in _frame.columns:
            _frame["source_name"] = _frame["source_name"].astype(str)
    return direction_df, pattern_df, population_df


@app.cell
def _(
    DEFAULT_ALPHA,
    DEFAULT_COLOR_DOMAIN,
    DEFAULT_POINT_SIZE,
    available_stat_columns,
    mo,
    population_df,
):
    source_options = sorted(population_df["source_name"].dropna().astype(str).unique())
    source_filter = mo.ui.multiselect(
        options=source_options,
        value=source_options,
        label="Sources",
    )

    candidate_significance_columns = available_stat_columns(population_df)
    numeric_sig_options = [
        c
        for c in candidate_significance_columns
        if c.startswith(("p_", "q_")) or "p_value" in c.lower() or "q_value" in c.lower()
    ]
    significance_options = ["Show all"] + numeric_sig_options
    # Start unfiltered so the app always shows the available population points.
    # The user can then choose any p/q column explicitly.
    default_sig = "p_motion_specific_two_sided"
    significance_filter = mo.ui.dropdown(
        options=significance_options,
        value=default_sig,
        label="Population filter",
    )
    alpha_filter = mo.ui.number(
        start=0.0,
        stop=1.0,
        step=0.001,
        value=DEFAULT_ALPHA,
        label="p/q threshold",
    )
    point_size = mo.ui.slider(
        start=15,
        stop=180,
        step=5,
        value=DEFAULT_POINT_SIZE,
        label="Point size",
    )
    color_domain = mo.ui.slider(
        start=0.25,
        stop=10.0,
        step=0.25,
        value=DEFAULT_COLOR_DOMAIN,
        label="Fraction-change color limit",
    )
    show_missing_coordinates = mo.ui.switch(
        value=False,
        label="Include rows missing coordinates",
    )

    controls = mo.hstack(
        [
            source_filter,
            significance_filter,
            alpha_filter,
            point_size,
            color_domain,
            show_missing_coordinates,
        ],
        widths=[2, 2, 1, 1, 1, 1],
        gap=1,
    )
    controls
    return (
        alpha_filter,
        color_domain,
        point_size,
        show_missing_coordinates,
        significance_filter,
        source_filter,
    )


@app.cell
def _(mo):
    mo.md("""
    # Neuropixels population explorer

    Click any point in any of the 12 pattern maps. The selected unit's full
    12-pattern response, 8-direction tuning, and p/q values appear below.
    """)
    return


@app.cell
def _(
    PATTERN_LABELS,
    PATTERN_ORDER,
    alpha_filter,
    alt,
    color_domain,
    np,
    point_size,
    population_df,
    show_missing_coordinates,
    significance_filter,
    source_filter,
):
    selected_sources = list(source_filter.value or [])
    population_visible = population_df[
        population_df["source_name"].isin(selected_sources)
    ].copy()

    chosen_sig = significance_filter.value
    if chosen_sig != "Show all" and chosen_sig in population_visible.columns:
        sig_values = population_visible[chosen_sig]
        if sig_values.dtype == bool:
            population_visible = population_visible[sig_values.fillna(False)].copy()
        else:
            sig_numeric = np.asarray(
                population_visible[chosen_sig].pipe(lambda s: __import__("pandas").to_numeric(s, errors="coerce"))
            )
            population_visible = population_visible[
                np.isfinite(sig_numeric) & (sig_numeric < float(alpha_filter.value))
            ].copy()

    if not show_missing_coordinates.value:
        population_visible = population_visible.dropna(
            subset=["x_plot_um", "y_plot_um"]
        )

    population_visible["pattern_label"] = population_visible["pattern"].map(
        PATTERN_LABELS
    ).fillna(population_visible["pattern"].astype(str))
    population_visible["pattern_label"] = __import__("pandas").Categorical(
        population_visible["pattern_label"],
        categories=[PATTERN_LABELS.get(p, p) for p in PATTERN_ORDER],
        ordered=True,
    )

    tooltip_columns = [
        c
        for c in [
            "source_name",
            "unit_id",
            "unit_uid",
            "pattern",
            "shank_id",
            "best_channel",
            "x_um",
            "y_um",
            "baseline_fr_mean",
            "moving_fr_mean",
            "fraction_change",
            chosen_sig if chosen_sig != "Show all" else None,
        ]
        if c is not None and c in population_visible.columns
    ]

    point_pick = alt.selection_point(
        fields=["unit_uid", "pattern"],
        on="click",
        clear="dblclick",
        empty=False,
        name="population_point_pick",
    )

    population_chart_spec = (
        alt.Chart(population_visible)
        .mark_circle(
            size=int(point_size.value),
            stroke="black",
        )
        .encode(
            x=alt.X(
                "x_plot_um:Q",
                title="M–L position (µm)",
                scale=alt.Scale(zero=False),
            ),
            y=alt.Y(
                "y_plot_um:Q",
                title="Depth (µm)",
                scale=alt.Scale(zero=False),
            ),
            color=alt.Color(
                "fraction_change:Q",
                title="Fraction change",
                scale=alt.Scale(
                    scheme="redblue",
                    domain=[-float(color_domain.value), float(color_domain.value)],
                    clamp=True,
                    reverse=True,
                ),
            ),
            tooltip=tooltip_columns,
            opacity=alt.condition(point_pick, alt.value(1.0), alt.value(0.72)),
            strokeWidth=alt.condition(point_pick, alt.value(2.8), alt.value(0.25)),
            size=alt.condition(
                point_pick,
                alt.value(int(point_size.value) * 1.8),
                alt.value(int(point_size.value)),
            ),
        )
        .add_params(point_pick)
        .properties(width=235, height=310)
        .facet(
            facet=alt.Facet(
                "pattern_label:N",
                title=None,
                sort=[PATTERN_LABELS.get(p, p) for p in PATTERN_ORDER],
                header=alt.Header(labelFontSize=13, labelLimit=220),
            ),
            columns=4,
        )
        .resolve_scale(x="shared", y="shared", color="shared")
        .properties(title="12-pattern population maps")
    )
    return population_chart_spec, population_visible


@app.cell
def _(
    mo,
    population_df,
    population_visible,
    significance_filter,
    source_filter,
):
    total_rows = len(population_df)
    visible_rows = len(population_visible)
    selected_sources_count = len(source_filter.value or [])
    diagnostic = mo.md(
        f"**Population rows:** {visible_rows:,} visible / {total_rows:,} total  "
        f"| **Sources selected:** {selected_sources_count}  "
        f"| **Filter:** `{significance_filter.value}`"
    )
    if visible_rows == 0:
        diagnostic = mo.callout(
            mo.vstack([
                diagnostic,
                mo.md(
                    "No population points remain after filtering. Choose **Show all**, "
                    "increase the p/q threshold, or check whether the selected statistic "
                    "contains numeric values."
                ),
            ]),
            kind="warn",
        )
    diagnostic
    return


@app.cell
def _(mo, population_chart_spec):
    population_selector = mo.ui.altair_chart(
        population_chart_spec,
        chart_selection=False,
        legend_selection=False,
        label="Click a population point (double-click to clear)",
    )
    population_selector
    return (population_selector,)


@app.cell
def _(population_selector, population_visible):
    selected_rows = population_selector.value
    if selected_rows is None:
        selected_rows = population_visible.iloc[0:0].copy()
    elif not hasattr(selected_rows, "columns"):
        selected_rows = population_visible.iloc[0:0].copy()

    if selected_rows.empty:
        selected_unit_uid = None
        selected_pattern = None
        selected_point = None
    else:
        # A point selection should normally contain one row. Taking the last row
        # also behaves sensibly if a browser keeps more than one selected point.
        selected_point = selected_rows.iloc[-1]
        selected_unit_uid = str(selected_point["unit_uid"])
        selected_pattern = str(selected_point["pattern"])
    return selected_pattern, selected_point, selected_unit_uid


@app.cell
def _(mo, selected_pattern, selected_point, selected_unit_uid):
    if selected_unit_uid is None:
        selected_unit_card = mo.callout(
            mo.md("Click a population point to load unit-level details."),
            kind="info",
        )
    else:
        metadata_fields = [
            ("Unit UID", selected_unit_uid),
            ("Source", selected_point.get("source_name", "")),
            ("Unit ID", selected_point.get("unit_id", "")),
            ("Selected pattern", selected_pattern),
            ("Shank", selected_point.get("shank_id", "")),
            ("Best channel", selected_point.get("best_channel", "")),
            ("x (µm)", selected_point.get("x_um", "")),
            ("y/depth (µm)", selected_point.get("y_um", "")),
        ]
        metadata_text = "  \n".join(
            f"**{label}:** {value}" for label, value in metadata_fields
        )
        selected_unit_card = mo.callout(mo.md(metadata_text), kind="neutral")

    selected_unit_card
    return


@app.cell
def _(
    PATTERN_LABELS,
    PATTERN_ORDER,
    first_existing,
    go,
    np,
    pattern_df,
    selected_pattern,
    selected_unit_uid,
):
    if selected_unit_uid is None:
        pattern_unit = pattern_df.iloc[0:0].copy()
        pattern_response_chart = go.Figure()
        pattern_response_chart.add_annotation(
            text="Select a population point to display the 12-pattern response.",
            x=0.5,
            y=0.5,
            xref="paper",
            yref="paper",
            showarrow=False,
        )
        pattern_response_chart.update_layout(
            height=360,
            xaxis={"visible": False},
            yaxis={"visible": False},
        )
    else:
        pattern_unit = pattern_df[
            pattern_df["unit_uid"].astype(str) == selected_unit_uid
        ].copy()

        pattern_unit["pattern_label"] = pattern_unit["pattern"].map(
            PATTERN_LABELS
        ).fillna(pattern_unit["pattern"].astype(str))
        pattern_to_x = {p: i for i, p in enumerate(PATTERN_ORDER)}
        pattern_unit["pattern_x"] = pattern_unit["pattern"].map(pattern_to_x)

        trial_value_col = first_existing(
            pattern_unit.columns,
            [
                "response_trial",
                "moving_minus_baseline",
                "moving_fr_minus_baseline",
            ],
        )

        if pattern_unit.empty or trial_value_col is None:
            pattern_response_chart = go.Figure()
            pattern_response_chart.add_annotation(
                text="No trial-level 12-pattern response data are available for this unit.",
                x=0.5,
                y=0.5,
                xref="paper",
                yref="paper",
                showarrow=False,
            )
            pattern_response_chart.update_layout(
                height=360,
                xaxis={"visible": False},
                yaxis={"visible": False},
            )
        else:
            import pandas as _pd

            pattern_plot = pattern_unit.copy()
            pattern_plot["response_trial_plot"] = _pd.to_numeric(
                pattern_plot[trial_value_col],
                errors="coerce",
            )
            pattern_plot = pattern_plot[
                pattern_plot["pattern_x"].notna()
                & pattern_plot["response_trial_plot"].notna()
            ].copy()

            # Deterministic horizontal jitter: the same trial always appears in
            # the same position after any reactive rerun.
            _rng = np.random.default_rng(42)
            _sort_cols = [
                c for c in ["pattern_x", "trial_id"]
                if c in pattern_plot.columns
            ]
            pattern_plot = pattern_plot.sort_values(
                _sort_cols,
                kind="stable",
            ).copy()
            pattern_plot["pattern_x_jitter"] = (
                pattern_plot["pattern_x"].astype(float)
                + _rng.normal(0.0, 0.075, size=len(pattern_plot))
            )

            pattern_trial_summary = (
                pattern_plot.groupby(
                    ["pattern", "pattern_label", "pattern_x"],
                    dropna=False,
                )["response_trial_plot"]
                .agg(["mean", "sem", "count"])
                .reset_index()
                .sort_values("pattern_x", kind="stable")
            )

            pattern_response_chart = go.Figure()

            # Raw trial observations.
            custom_columns = [
                pattern_plot["pattern_label"].astype(str),
                pattern_plot["trial_id"].astype(str),
            ]
            pattern_response_chart.add_trace(
                go.Scatter(
                    x=pattern_plot["pattern_x_jitter"],
                    y=pattern_plot["response_trial_plot"],
                    mode="markers",
                    name="Raw trials",
                    marker={
                        "size": 6,
                        "opacity": 0.48,
                    },
                    customdata=np.column_stack(custom_columns),
                    hovertemplate=(
                        "Pattern: %{customdata[0]}<br>"
                        "Trial: %{customdata[1]}<br>"
                        "Moving − baseline FR: %{y:.4g}"
                        "<extra></extra>"
                    ),
                )
            )

            # Mean response line with SEM.
            mean_sizes = [
                12 if str(p) == str(selected_pattern) else 8
                for p in pattern_trial_summary["pattern"]
            ]
            mean_widths = [
                3 if str(p) == str(selected_pattern) else 1
                for p in pattern_trial_summary["pattern"]
            ]
            pattern_response_chart.add_trace(
                go.Scatter(
                    x=pattern_trial_summary["pattern_x"],
                    y=pattern_trial_summary["mean"],
                    mode="lines+markers",
                    name="Mean ± SEM",
                    error_y={
                        "type": "data",
                        "array": pattern_trial_summary["sem"].fillna(0.0),
                        "visible": True,
                        "thickness": 1.3,
                        "width": 4,
                    },
                    marker={
                        "size": mean_sizes,
                        "line": {"width": mean_widths},
                    },
                    customdata=np.column_stack(
                        [
                            pattern_trial_summary["pattern_label"].astype(str),
                            pattern_trial_summary["sem"].fillna(0.0),
                            pattern_trial_summary["count"],
                        ]
                    ),
                    hovertemplate=(
                        "Pattern: %{customdata[0]}<br>"
                        "Mean response: %{y:.4g}<br>"
                        "SEM: %{customdata[1]:.4g}<br>"
                        "n trials: %{customdata[2]}"
                        "<extra></extra>"
                    ),
                )
            )

            pattern_response_chart.add_hline(
                y=0,
                line_dash="dash",
                line_width=1,
            )
            pattern_response_chart.update_layout(
                title=f"{selected_unit_uid}: full 12-pattern response",
                height=430,
                margin={"l": 70, "r": 25, "t": 60, "b": 115},
                xaxis={
                    "title": "Pattern",
                    "tickmode": "array",
                    "tickvals": list(range(len(PATTERN_ORDER))),
                    "ticktext": [
                        PATTERN_LABELS.get(p, p)
                        for p in PATTERN_ORDER
                    ],
                    "tickangle": -35,
                    "range": [-0.45, len(PATTERN_ORDER) - 0.55],
                },
                yaxis={"title": "Moving − baseline FR"},
                legend={
                    "orientation": "h",
                    "yanchor": "bottom",
                    "y": 1.02,
                    "xanchor": "left",
                    "x": 0,
                },
                hovermode="closest",
            )
    return pattern_response_chart, pattern_unit


@app.cell
def _(mo, pattern_response_chart, selected_unit_uid):
    if selected_unit_uid is not None:
        mo.md("## 12-pattern response")
    mo.ui.plotly(pattern_response_chart)
    return


@app.cell
def _(
    DIRECTION_ORDER,
    SCREEN_ORDER,
    direction_df,
    go,
    np,
    pd,
    selected_unit_uid,
):
    if selected_unit_uid is None:
        direction_unit = direction_df.iloc[0:0].copy()
    else:
        direction_unit = direction_df[
            direction_df["unit_uid"].astype(str) == selected_unit_uid
        ].copy()

    def _empty_plotly(title, message):
        fig = go.Figure()
        fig.add_annotation(
            text=message, x=0.5, y=0.5, xref="paper", yref="paper",
            showarrow=False, font=dict(size=15),
        )
        fig.update_xaxes(visible=False)
        fig.update_yaxes(visible=False)
        fig.update_layout(title=title, height=330, margin=dict(l=35, r=25, t=55, b=35))
        return fig

    direction_panels = []
    for screen_name in SCREEN_ORDER:
        screen_data = direction_unit[
            direction_unit["screen_role"].astype(str).str.lower() == screen_name
        ].copy()

        if screen_data.empty:
            polar_fig = _empty_plotly(
                f"{screen_name.title()}: baseline vs moving",
                f"No {screen_name} 8-direction data",
            )
            line_fig = _empty_plotly(
                f"{screen_name.title()}: direction response",
                f"No {screen_name} 8-direction data",
            )
        else:
            for col in ["direction", "baseline_fr_trial", "moving_fr_trial", "response_trial"]:
                screen_data[col] = pd.to_numeric(screen_data[col], errors="coerce")

            summary = (
                screen_data.groupby("direction", as_index=False, dropna=False)
                .agg(
                    baseline_fr_mean=("baseline_fr_trial", "mean"),
                    moving_fr_mean=("moving_fr_trial", "mean"),
                    response_mean=("response_trial", "mean"),
                    response_sd=("response_trial", "std"),
                    response_n=("response_trial", "count"),
                )
            )
            summary["response_sem"] = summary["response_sd"] / np.sqrt(
                summary["response_n"].clip(lower=1)
            )
            summary["direction_order"] = summary["direction"].map(
                {float(d): i for i, d in enumerate(DIRECTION_ORDER)}
            )
            summary = summary.sort_values(["direction_order", "direction"], kind="stable")

            # Plotly Scatterpolar accepts angular coordinates in degrees.
            theta = summary["direction"].tolist()
            baseline_r = summary["baseline_fr_mean"].clip(lower=0).tolist()
            moving_r = summary["moving_fr_mean"].clip(lower=0).tolist()
            if theta:
                theta_closed = theta + [theta[0]]
                baseline_closed = baseline_r + [baseline_r[0]]
                moving_closed = moving_r + [moving_r[0]]
            else:
                theta_closed, baseline_closed, moving_closed = [], [], []

            polar_fig = go.Figure()
            polar_fig.add_trace(
                go.Scatterpolar(
                    theta=theta_closed,
                    r=baseline_closed,
                    mode="lines+markers",
                    name="Baseline FR",
                    hovertemplate="Direction %{theta}°<br>Baseline %{r:.3g} Hz<extra></extra>",
                )
            )
            polar_fig.add_trace(
                go.Scatterpolar(
                    theta=theta_closed,
                    r=moving_closed,
                    mode="lines+markers",
                    name="Moving FR",
                    hovertemplate="Direction %{theta}°<br>Moving %{r:.3g} Hz<extra></extra>",
                )
            )
            polar_fig.update_layout(
                title=f"{screen_name.title()}: baseline vs moving",
                height=360,
                margin=dict(l=55, r=45, t=60, b=35),
                polar=dict(
                    angularaxis=dict(
                        direction="clockwise",
                        rotation=90,
                        tickmode="array",
                        tickvals=DIRECTION_ORDER,
                        ticktext=[f"{d}°" for d in DIRECTION_ORDER],
                    ),
                    radialaxis=dict(rangemode="tozero"),
                ),
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
            )

            # Stable per-trial horizontal jitter, independent of app refreshes.
            jitter_key = screen_data[["unit_uid", "screen_role", "direction", "trial_id"]].astype(str)
            hashed = pd.util.hash_pandas_object(jitter_key, index=False).astype("uint64")
            screen_data["direction_jitter"] = screen_data["direction"] + (
                (hashed % 10001).astype(float) / 10000.0 - 0.5
            ) * 10.0

            line_fig = go.Figure()
            line_fig.add_trace(
                go.Scatter(
                    x=screen_data["direction_jitter"],
                    y=screen_data["response_trial"],
                    mode="markers",
                    name="Raw trials",
                    marker=dict(size=7, opacity=0.48),
                    customdata=np.column_stack(
                        [screen_data["trial_id"].astype(str), screen_data["direction"]]
                    ),
                    hovertemplate=(
                        "Trial %{customdata[0]}<br>Direction %{customdata[1]}°"
                        "<br>Moving − baseline %{y:.3g} Hz<extra></extra>"
                    ),
                )
            )
            line_fig.add_trace(
                go.Scatter(
                    x=summary["direction"],
                    y=summary["response_mean"],
                    mode="lines+markers",
                    name="Mean ± SEM",
                    error_y=dict(
                        type="data",
                        array=summary["response_sem"].fillna(0).to_numpy(),
                        visible=True,
                    ),
                    hovertemplate=(
                        "Direction %{x}°<br>Mean %{y:.3g} Hz"
                        "<br>SEM %{error_y.array:.3g}<extra></extra>"
                    ),
                )
            )
            line_fig.add_hline(y=0, line_dash="dash")
            line_fig.update_layout(
                title=f"{screen_name.title()}: direction response",
                height=360,
                margin=dict(l=60, r=35, t=60, b=55),
                xaxis=dict(
                    title="Direction (deg)",
                    tickmode="array",
                    tickvals=DIRECTION_ORDER,
                    range=[-18, 333],
                ),
                yaxis=dict(title="Moving − baseline FR (Hz)"),
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
            )

        direction_panels.append((screen_name, polar_fig, line_fig))
    return direction_panels, direction_unit


@app.cell
def _(direction_panels, mo, selected_unit_uid):
    if selected_unit_uid is None:
        direction_display = mo.callout(
            mo.md("Select a unit to display 8-direction results."), kind="info"
        )
    else:
        rows = []
        for _screen, _polar, _line in direction_panels:
            rows.append(mo.hstack([_polar, _line], widths=[1, 1.35], gap=1))
        direction_display = mo.vstack(rows, gap=1)

    mo.md("## 8-direction summary")
    direction_display
    return


@app.cell
def _(
    available_stat_columns,
    direction_unit,
    pattern_unit,
    selected_pattern,
    stat_table_long,
):
    pattern_stat_columns = available_stat_columns(pattern_unit)
    direction_stat_columns = available_stat_columns(direction_unit)

    # Pattern-level p/q values are repeated on every trial row. Keep one row
    # per pattern before making the long statistics table.
    _pattern_stat_source = pattern_unit.drop_duplicates(
        ["source_name", "unit_id", "unit_uid", "pattern"],
        keep="first",
    )

    pattern_stats_long = stat_table_long(
        _pattern_stat_source,
        ["source_name", "unit_id", "unit_uid", "pattern", "pattern_order"],
        pattern_stat_columns,
    )
    if not pattern_stats_long.empty:
        pattern_stats_long["selected_pattern"] = (
            pattern_stats_long["pattern"].astype(str) == str(selected_pattern)
        )
        pattern_stats_long = pattern_stats_long.sort_values(
            ["pattern_order", "statistic"], kind="stable"
        )

    direction_stats_long = stat_table_long(
        direction_unit,
        [
            "source_name",
            "unit_id",
            "unit_uid",
            "screen_role",
            "speed",
            "direction",
            "screen_order",
            "direction_order",
        ],
        direction_stat_columns,
    )
    if not direction_stats_long.empty:
        direction_stats_long = direction_stats_long.sort_values(
            ["screen_order", "speed", "direction_order", "statistic"],
            kind="stable",
        )
    return direction_stats_long, pattern_stats_long


@app.cell
def _(direction_stats_long, mo, pattern_stats_long, selected_unit_uid):
    if selected_unit_uid is None:
        stats_display = mo.callout(
            mo.md("Select a unit to display p/q values."), kind="info"
        )
    else:
        pattern_table = (
            mo.ui.table(
                pattern_stats_long,
                label="12-pattern p/q values",
                pagination=True,
                page_size=24,
                selection=None,
            )
            if not pattern_stats_long.empty
            else mo.callout(mo.md("No 12-pattern p/q columns found."), kind="warn")
        )
        direction_table = (
            mo.ui.table(
                direction_stats_long,
                label="8-direction p/q values",
                pagination=True,
                page_size=24,
                selection=None,
            )
            if not direction_stats_long.empty
            else mo.callout(mo.md("No 8-direction p/q data found."), kind="warn")
        )
        stats_display = mo.ui.tabs(
            {
                "12-pattern statistics": pattern_table,
                "8-direction statistics": direction_table,
            }
        )

    mo.md("## Statistical results")
    stats_display
    return


@app.cell
def _(direction_df, mo, pattern_df, population_df):
    data_summary = mo.md(
        f"""
        ---
        **Loaded data**

        - Population points: **{len(population_df):,} rows**, **{population_df['unit_uid'].nunique():,} units**
        - 12-pattern responses: **{len(pattern_df):,} rows**
        - 8-direction responses: **{len(direction_df):,} rows**
        """
    )
    data_summary
    return


if __name__ == "__main__":
    app.run()
