import spikeinterface.full as si
from multiprocessing import freeze_support
from config_local import OUTPUT_DIR, WORKING_DIR


# =====================
# Global settings
# =====================

PREPROCESSED_FOLDER = WORKING_DIR / f"preprocessed_M12"

CURATED_SORTING_FOLDERS = {
    "kilosort4": WORKING_DIR / f"sorting_M12_kilosort4_curated",
    "mountainsort5": WORKING_DIR / f"sorting_M12_mountainsort5_curated",
}

ANALYZER_FOLDERS = {
    name: WORKING_DIR / f"analyzer_M12_{name}_curated"
    for name in CURATED_SORTING_FOLDERS
}

PHY_FOLDERS = {
    name: OUTPUT_DIR / f"phy_M12_{name}_curated"
    for name in CURATED_SORTING_FOLDERS
}

QUALITY_METRIC_NAMES = [
    "snr",
    "isi_violation",
    "firing_rate",
    "presence_ratio",
]


def export_one_sorter_to_phy(sorter_name, recording):
    curated_sorting_folder = CURATED_SORTING_FOLDERS[sorter_name]
    analyzer_folder = ANALYZER_FOLDERS[sorter_name]
    phy_folder = PHY_FOLDERS[sorter_name]

    print(f"\n===== Exporting {sorter_name} to Phy =====")

    if not curated_sorting_folder.exists():
        print(f"Skipping {sorter_name}: curated sorting folder not found")
        print(curated_sorting_folder)
        return

    # 1. Load curated sorting generated by Post_sorting_test.py.
    sorting = si.load(curated_sorting_folder)

    print("Curated sorting:")
    print(sorting)
    print("Curated spike counts:")
    print(sorting.count_num_spikes_per_unit())

    # 2. Create analyzer.
    analyzer = si.create_sorting_analyzer(
        sorting=sorting,
        recording=recording,
        format="binary_folder",
        folder=analyzer_folder,
        overwrite=True,
    )

    # 3. Compute extensions needed for waveform inspection, metrics, and Phy export.
    analyzer.compute("random_spikes")
    analyzer.compute("waveforms")
    analyzer.compute("templates")
    analyzer.compute("noise_levels")

    analyzer.compute(
        "quality_metrics",
        metric_names=QUALITY_METRIC_NAMES,
    )

    metrics = analyzer.get_extension("quality_metrics").get_data()

    print("\nQuality metrics:")
    print(metrics)

    metrics.to_csv(
        WORKING_DIR / f"quality_metrics_M12_{sorter_name}_curated.csv"
    )

    # 4. Export to Phy.
    si.export_to_phy(
        analyzer,
        output_folder=phy_folder,
        remove_if_exists=True,
    )

    print(f"Exported Phy folder: {phy_folder}")


def main():
    # Load preprocessed recording only here, because analyzer / Phy export needs recording.
    recording_saved = si.load(PREPROCESSED_FOLDER)

    # Your sorter outputs are 1 segment, so use the first segment only.
    recording_test = recording_saved.select_segments([0])

    for sorter_name in CURATED_SORTING_FOLDERS:
        export_one_sorter_to_phy(sorter_name, recording_test)


if __name__ == "__main__":
    freeze_support()
    main()
