import spikeinterface.full as si
from multiprocessing import freeze_support
from config_local import OUTPUT_DIR, WORKING_DIR, SEGMENT_INDEX_TO_USE
import pandas as pd


# =====================
# Global settings
# =====================

PREPROCESSED_FOLDER = WORKING_DIR / f"preprocessed_M12"

CURATED_SORTING_FOLDERS = {
    "kilosort4": WORKING_DIR / f"sorting_M12_kilosort4_curated",
    "mountainsort5": WORKING_DIR / f"sorting_M12_mountainsort5_curated",
}

ANALYZER_FOLDERS = {
    name: WORKING_DIR / f"analyzer_M12_{name}_curated"
    for name in CURATED_SORTING_FOLDERS
}

PHY_FOLDERS = {
    name: OUTPUT_DIR / f"phy_M12_{name}_curated"
    for name in CURATED_SORTING_FOLDERS
}

QUALITY_METRIC_NAMES = [
    "snr",
    "isi_violation",
    "firing_rate",
    "presence_ratio",
]

def load_phy_cluster_info(sorter_name):
    """
    Load Phy/Kilosort cluster_info.tsv if available.
    This contains fields such as KSLabel, ContamPct, group, ch, depth, n_spikes, etc.
    """
    # First try raw sorter output folder
    sorter_output_folder = WORKING_DIR / f"{sorter_name}_M12_test_output"
    cluster_info_path = sorter_output_folder / "cluster_info.tsv"

    # If not found, try exported Phy folder
    if not cluster_info_path.exists():
        cluster_info_path = PHY_FOLDERS[sorter_name] / "cluster_info.tsv"

    if not cluster_info_path.exists():
        print(f"No cluster_info.tsv found for {sorter_name}")
        return None

    print(f"Loading cluster info from: {cluster_info_path}")

    cluster_info = pd.read_csv(cluster_info_path, sep="\t")

    if "cluster_id" in cluster_info.columns:
        cluster_info = cluster_info.rename(columns={"cluster_id": "unit_id"})

    cluster_info["unit_id"] = cluster_info["unit_id"].astype(str)

    return cluster_info

def export_one_sorter_to_phy(sorter_name, recording):
    curated_sorting_folder = CURATED_SORTING_FOLDERS[sorter_name]
    analyzer_folder = ANALYZER_FOLDERS[sorter_name]
    phy_folder = PHY_FOLDERS[sorter_name]

    print(f"\n===== Exporting {sorter_name} to Phy =====")

    if not curated_sorting_folder.exists():
        print(f"Skipping {sorter_name}: curated sorting folder not found")
        print(curated_sorting_folder)
        return

    # 1. Load curated sorting generated by Post_sorting_test.py.
    sorting = si.load(curated_sorting_folder)

    print("Curated sorting:")
    print(sorting)
    print("Curated spike counts:")
    print(sorting.count_num_spikes_per_unit())

    # 2. Create analyzer.
    analyzer = si.create_sorting_analyzer(
        sorting=sorting,
        recording=recording,
        format="binary_folder",
        folder=analyzer_folder,
        overwrite=True,
    )

    # 3. Compute extensions needed for waveform inspection, metrics, and Phy export.
    analyzer.compute("random_spikes")
    analyzer.compute("waveforms")
    analyzer.compute("templates")
    analyzer.compute("noise_levels")

    analyzer.compute(
        "quality_metrics",
        metric_names=QUALITY_METRIC_NAMES,
    )

    metrics = analyzer.get_extension("quality_metrics").get_data()

    metrics_out = metrics.copy()
    metrics_out.index = metrics_out.index.astype(str)
    metrics_out.index.name = "unit_id"
    metrics_out = metrics_out.reset_index()

    cluster_info = load_phy_cluster_info(sorter_name)

    if cluster_info is not None:
        metrics_out = metrics_out.merge(
            cluster_info,
            on="unit_id",
            how="left",
            suffixes=("", "_phy"),
        )

    print("\nQuality metrics + Phy/Kilosort cluster info:")
    print(metrics_out)

    metrics_out.to_csv(
        WORKING_DIR / f"quality_metrics_M12_{sorter_name}_curated_with_phy_info.csv",
        index=False,
    )

    print("\nQuality metrics:")
    print(metrics)

    # metrics.to_csv(
    #     WORKING_DIR / f"quality_metrics_M12_{sorter_name}_curated.csv"
    # )

    # 4. Export to Phy.
    si.export_to_phy(
        analyzer,
        output_folder=phy_folder,
        remove_if_exists=True,
        # compute_pc_features=False,
        # compute_amplitudes=False,
    )

    print(f"Exported Phy folder: {phy_folder}")


def main():
    # Load preprocessed recording only here, because analyzer / Phy export needs recording.
    recording_saved = si.load(PREPROCESSED_FOLDER)

    # Your sorter outputs are 1 segment, so use the first segment only.
    recording_test = recording_saved.select_segments([SEGMENT_INDEX_TO_USE])

    for sorter_name in CURATED_SORTING_FOLDERS:
        export_one_sorter_to_phy(sorter_name, recording_test)


if __name__ == "__main__":
    freeze_support()
    main()
